
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('spell').del()
    .then(function () {
      // Inserts seed entries
      return knex('spell').insert([
        {
          id: 1,
          name: 'Acid Splash',
          level: 0,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Conjuration',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 211
        },
        {
          id: 2,
          name: 'Blade Ward',
          level: 0,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S',
          duration: '1 Round',
          school: 'Abjuration',
          target: 'Self',
          area_of_effect: '',
          phb_page: 218
        },
        {
          id: 3,
          name: 'Chill Touch',
          level: 0,
          casting_time: '1 Action',
          range: '120 ft',
          components: 'V, S',
          duration: '1 Round',
          school: 'Necromancy',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 221
        },
        {
          id: 4,
          name: 'Dancing Lights',
          level: 0,
          casting_time: '1 Action',
          range: '120 ft',
          components: 'V, S, M',
          duration: 'Concentration, up to 1 minute',
          school: 'Evocation',
          target: '',
          area_of_effect: '',
          phb_page: 230
        },
        {
          id: 5,
          name: 'Druidcraft',
          level: 0,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Transmutation',
          target: '',
          area_of_effect: '',
          phb_page: 236
        },
        {
          id: 6,
          name: 'Eldritch Blast',
          level: 0,
          casting_time: '1 Action',
          range: '120 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'Up to One Creature per Beam',
          area_of_effect: '',
          phb_page: 237
        },
        {
          id: 7,
          name: 'Fire Bolt',
          level: 0,
          casting_time: '1 Action',
          range: '120 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'One Creature or Object',
          area_of_effect: '',
          phb_page: 242
        },
        {
          id: 8,
          name: 'Friends',
          level: 0,
          casting_time: '1 Action',
          range: 'Self',
          components: 'S, M',
          duration: 'Concentration, up to 1 minute',
          school: 'Enchantment',
          target: 'One Creature not Hostile to you',
          area_of_effect: '',
          phb_page: 244
        },
        {
          id: 9,
          name: 'Guidance',
          level: 0,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S',
          duration: 'Concentration, up to 1 minute',
          school: 'Divination',
          target: 'One Willing Creature',
          area_of_effect: '',
          phb_page: 248
        },
        {
          id: 10,
          name: 'Light',
          level: 0,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, M',
          duration: '1 hour',
          school: 'Evocation',
          target: 'One Object',
          area_of_effect: '',
          phb_page: 255
        },
        {
          id: 11,
          name: 'Mage Hand',
          level: 0,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S',
          duration: '1 minute',
          school: 'Conjuration',
          target: 'An Object',
          area_of_effect: '',
          phb_page: 256
        },
        {
          id: 12,
          name: 'Mending',
          level: 0,
          casting_time: '1 minute',
          range: 'Touch',
          components: 'V, S, M',
          duration: 'Instantaneous',
          school: 'Transmutation',
          target: 'One Object',
          area_of_effect: '',
          phb_page: 259
        },
        {
          id: 13,
          name: 'Message',
          level: 0,
          casting_time: '1 Action',
          range: '120 ft',
          components: 'V, S, M',
          duration: '1 round',
          school: 'Transmutation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 259
        },
        {
          id: 14,
          name: 'Minor Illusion',
          level: 0,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'S, M',
          duration: '1 minute',
          school: 'Illusion',
          target: '',
          area_of_effect: '',
          phb_page: 260
        },
        {
          id: 15,
          name: 'Poison Spray',
          level: 0,
          casting_time: '1 Action',
          range: '10 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Conjuration',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 266
        },
        {
          id: 16,
          name: 'Prestidigitation',
          level: 0,
          casting_time: '1 Action',
          range: '10 ft',
          components: 'V, S',
          duration: 'Up to 1 hour',
          school: 'Transmutation',
          target: '',
          area_of_effect: '',
          phb_page: 267
        },
        {
          id: 17,
          name: 'Produce Flame',
          level: 0,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S',
          duration: '10 minutes',
          school: 'Conjuration',
          target: '',
          area_of_effect: '',
          phb_page: 268
        },
        {
          id: 18,
          name: 'Ray of Frost',
          level: 0,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 271
        },
        {
          id: 19,
          name: 'Resistance',
          level: 0,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S, M',
          duration: 'Concentration, up to 1 minute',
          school: 'Abjuration',
          target: 'One Willing Creature',
          area_of_effect: '',
          phb_page: 272
        },
        {
          id: 20,
          name: 'Sacred Flame',
          level: 0,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 272
        },
        {
          id: 21,
          name: 'Shillelagh',
          level: 0,
          casting_time: '1 Bonus Action',
          range: 'Touch',
          components: 'V, S, M',
          duration: '1 minute',
          school: 'Transmutation',
          target: 'Wood Club or Quarterstaff',
          area_of_effect: '',
          phb_page: 275
        },
        {
          id: 22,
          name: 'Shocking Grasp',
          level: 0,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 275
        },
        {
          id: 23,
          name: 'Spare the Dying',
          level: 0,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Necromancy',
          target: 'A living creature at 0 hp',
          area_of_effect: '',
          phb_page: 277
        },
        {
          id: 24,
          name: 'Thaumaturgy',
          level: 0,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V',
          duration: 'Up to 1 minute',
          school: 'Transmutation',
          target: '',
          area_of_effect: '',
          phb_page: 282
        },
        {
          id: 25,
          name: 'Thorn Whip',
          level: 0,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: 'Instantaneous',
          school: 'Transmutation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 282
        },
        {
          id: 26,
          name: 'True Strike',
          level: 0,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'S',
          duration: 'Concentration, up to 1 round',
          school: 'Divination',
          target: 'One Creature or Object you can attack',
          area_of_effect: '',
          phb_page: 284
        },
        {
          id: 27,
          name: 'Vicious Mockery',
          level: 0,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V',
          duration: 'Instantaneous',
          school: 'Enchantment',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 285
        },
        {
          id: 28,
          name: 'Alarm',
          level: 1,
          casting_time: '1 Minute',
          range: '30 ft',
          components: 'V, S, M',
          duration: '8 hours',
          school: 'Abjuration',
          target: 'A door, window, or area no larger than a 20-ft cube',
          area_of_effect: '',
          phb_page: 211
        },
        {
          id: 29,
          name: 'Animal Friendship',
          level: 1,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: '24 hours',
          school: 'Enchantment',
          target: 'One Beast',
          area_of_effect: '',
          phb_page: 212
        },
        {
          id: 30,
          name: 'Armor of Agathys',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S, M',
          duration: '1 hour',
          school: 'Abjuration',
          target: '',
          area_of_effect: '',
          phb_page: 215
        },
        {
          id: 31,
          name: 'Arms of Hadar',
          level: 1,
          casting_time: '1 Action',
          range: 'Self (10 ft radius)',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Conjuration',
          target: 'All Creatures within 10 ft of you',
          area_of_effect: '',
          phb_page: 215
        },
        {
          id: 32,
          name: 'Bane',
          level: 1,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: 'Concentration, up to 1 minute',
          school: 'Enchantment',
          target: 'Up to three creatures you can see',
          area_of_effect: '',
          phb_page: 216
        },
        {
          id: 33,
          name: 'Bless',
          level: 1,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: 'Concentration, up to 1 minute',
          school: 'Enchantment',
          target: 'Up to three creatures',
          area_of_effect: '',
          phb_page: 219
        },
        {
          id: 34,
          name: 'Burning Hands',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'Each Creature in the Cone',
          area_of_effect: '15-ft Cone',
          phb_page: 220
        },
        {
          id: 35,
          name: 'Charm Person',
          level: 1,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S',
          duration: '1 hour',
          school: 'Enchantment',
          target: 'One Humanoid',
          area_of_effect: '',
          phb_page: 221
        },
        {
          id: 36,
          name: 'Chromatic Orb',
          level: 1,
          casting_time: '1 Action',
          range: '90 ft',
          components: 'V, S, M',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 221
        },
        {
          id: 37,
          name: 'Color Spray',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S, M',
          duration: '1 round',
          school: 'Illusion',
          target: 'Creatures in the Cone',
          area_of_effect: '15-ft Cone',
          phb_page: 222
        },
        {
          id: 38,
          name: 'Command',
          level: 1,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V',
          duration: '1 round',
          school: 'Enchantment',
          target: 'One Creature you can see',
          area_of_effect: '',
          phb_page: 223
        },
        {
          id: 39,
          name: 'Compelled Duel',
          level: 1,
          casting_time: '1 Bonus Action',
          range: '30 ft',
          components: 'V',
          duration: 'Concentration, up to 1 minute',
          school: 'Enchantment',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 224
        },
        {
          id: 40,
          name: 'Comprehend Languages',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S, M',
          duration: '1 hour',
          school: 'Divination',
          target: '',
          area_of_effect: '',
          phb_page: 224
        },
        {
          id: 41,
          name: 'Create or Destroy Water',
          level: 1,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: 'Instantaneous',
          school: 'Transmutation',
          target: '',
          area_of_effect: '',
          phb_page: 229
        },
        {
          id: 42,
          name: 'Cure Wounds',
          level: 1,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 230
        },
        {
          id: 43,
          name: 'Detect Evil and Good',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S',
          duration: 'Concentration, up to 10 minutes',
          school: 'Divination',
          target: '',
          area_of_effect: '',
          phb_page: 231
        },
        {
          id: 44,
          name: 'Detect Magic',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S',
          duration: 'Concentration, up to 10 minutes',
          school: 'Divination',
          target: '',
          area_of_effect: '',
          phb_page: 231
        },
        {
          id: 45,
          name: 'Detect Poison and Disease',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S, M',
          duration: 'Concentration, up to 10 minutes',
          school: 'Divination',
          target: '',
          area_of_effect: '',
          phb_page: 231
        },
        {
          id: 46,
          name: 'Disguise Self',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S',
          duration: '1 hour',
          school: 'Illusion',
          target: '',
          area_of_effect: '',
          phb_page: 233
        },
        {
          id: 47,
          name: 'Dissonant Whispers',
          level: 1,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V',
          duration: 'Instantaneous',
          school: 'Enchantment',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 234
        },
        {
          id: 48,
          name: 'Divine Favor',
          level: 1,
          casting_time: '1 Bonus Action',
          range: 'Self',
          components: 'V, S',
          duration: 'Concentration, up to 1 minute',
          school: 'Evocation',
          target: '',
          area_of_effect: '',
          phb_page: 234
        },
        {
          id: 49,
          name: 'Ensnaring Strike',
          level: 1,
          casting_time: '1 Bonus Action',
          range: 'Self',
          components: 'V',
          duration: 'Concentration, up to 1 minute',
          school: 'Conjuration',
          target: '',
          area_of_effect: '',
          phb_page: 237
        },
        {
          id: 50,
          name: 'Entangle',
          level: 1,
          casting_time: '1 Action',
          range: '90 ft',
          components: 'V, S',
          duration: 'Concentration, up to 1 minute',
          school: 'Conjuration',
          target: '',
          area_of_effect: '20 ft Square',
          phb_page: 238
        },
        {
          id: 51,
          name: 'Expeditious Retreat',
          level: 1,
          casting_time: '1 Bonus Action',
          range: 'Self',
          components: 'V, S',
          duration: 'Concentration, up to 10 minutes',
          school: 'Transmutation',
          target: '',
          area_of_effect: '',
          phb_page: 238
        },
        {
          id: 52,
          name: 'Faerie Fire',
          level: 1,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V',
          duration: 'Concentration, up to 1 minute',
          school: 'Evocation',
          target: '',
          area_of_effect: '20 ft Cube',
          phb_page: 239
        },
        {
          id: 53,
          name: 'False Life',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S, M',
          duration: '1 hour',
          school: 'Necromancy',
          target: '',
          area_of_effect: '',
          phb_page: 239
        },
        {
          id: 54,
          name: 'Feather Fall',
          level: 1,
          casting_time: '1 Reaction',
          range: '60 ft',
          components: 'V, M',
          duration: '1 minute',
          school: 'Transmutation',
          target: 'Up to 5 falling creatures',
          area_of_effect: '',
          phb_page: 239
        },
        {
          id: 55,
          name: 'Find Familiar',
          level: 1,
          casting_time: '1 hour',
          range: '10 ft',
          components: 'V, S, M',
          duration: 'Instantaneous',
          school: 'Conjuration',
          target: '',
          area_of_effect: '',
          phb_page: 240
        },
        {
          id: 56,
          name: 'Fog Cloud',
          level: 1,
          casting_time: '1 Action',
          range: '120 ft',
          components: 'V, S',
          duration: 'Concentration, up to 1 hour',
          school: 'Conjuration',
          target: '',
          area_of_effect: '20 ft radius Sphere',
          phb_page: 243
        },
        {
          id: 57,
          name: 'Goodberry',
          level: 1,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S, M',
          duration: 'Instantaneous',
          school: 'Transmutation',
          target: '',
          area_of_effect: '',
          phb_page: 246
        },
        {
          id: 58,
          name: 'Grease',
          level: 1,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V, S, M',
          duration: '1 minute',
          school: 'Conjuration',
          target: '',
          area_of_effect: '10 ft Square',
          phb_page: 246
        },
        {
          id: 59,
          name: 'Guiding Bolt',
          level: 1,
          casting_time: '1 Action',
          range: '120 ft',
          components: 'V, S',
          duration: '1 Round',
          school: 'Evocation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 248
        },
        {
          id: 60,
          name: 'Hail of Thorns',
          level: 1,
          casting_time: '1 Bonus Action',
          range: 'Self',
          components: 'V',
          duration: 'Concentration, up to 1 minute',
          school: 'Conjuration',
          target: '',
          area_of_effect: '',
          phb_page: 249
        },
        {
          id: 61,
          name: 'Healing Word',
          level: 1,
          casting_time: '1 Bonus Action',
          range: '60 ft',
          components: 'V',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 250
        },
        {
          id: 62,
          name: 'Hellish Rebuke',
          level: 1,
          casting_time: '1 Reaction',
          range: '60 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'The Creature that just damaged you',
          area_of_effect: '',
          phb_page: 250
        },
        {
          id: 63,
          name: 'Heroism',
          level: 1,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S',
          duration: 'Concentration, up to 1 minute',
          school: 'Enchantment',
          target: 'One Willing Creature',
          area_of_effect: '',
          phb_page: 250
        },
        {
          id: 64,
          name: 'Hex',
          level: 1,
          casting_time: '1 Bonus Action',
          range: '90 ft',
          components: 'V, S, M',
          duration: 'Concentration, up to 1 hour',
          school: 'Enchantment',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 251
        },
        {
          id: 65,
          name: "Hunter's Mark",
          level: 1,
          casting_time: '1 Bonus Action',
          range: '90 ft',
          components: 'V',
          duration: 'Concentration, up to 1 hour',
          school: 'Divination',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 251
        },
        {
          id: 66,
          name: 'Identify',
          level: 1,
          casting_time: '1 Minute',
          range: 'Touch',
          components: 'V, S, M',
          duration: 'Instantaneous',
          school: 'Divination',
          target: 'One Object or Creature',
          area_of_effect: '',
          phb_page: 252
        },
        {
          id: 67,
          name: 'Illusory Script',
          level: 1,
          casting_time: '1 Minute',
          range: 'Touch',
          components: 'S, M',
          duration: '10 days',
          school: 'Illusion',
          target: '',
          area_of_effect: '',
          phb_page: 252
        },
        {
          id: 68,
          name: 'Inflict Wounds',
          level: 1,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Necromancy',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 253
        },
        {
          id: 69,
          name: 'Jump',
          level: 1,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S, M',
          duration: '1 Minute',
          school: 'Transmutation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 254
        },
        {
          id: 70,
          name: 'Longstrider',
          level: 1,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S, M',
          duration: '1 hour',
          school: 'Transmutation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 256
        },
        {
          id: 71,
          name: 'Mage Armor',
          level: 1,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S, M',
          duration: '8 hours',
          school: 'Abjuration',
          target: "One Willing Creature who isn't wearing armor",
          area_of_effect: '',
          phb_page: 256
        },
        {
          id: 72,
          name: 'Magic Missile',
          level: 1,
          casting_time: '1 Action',
          range: '120 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: 'One Creature per dart',
          area_of_effect: '',
          phb_page: 257
        },
        {
          id: 73,
          name: 'Protection from Evil and Good',
          level: 1,
          casting_time: '1 Action',
          range: 'Touch',
          components: 'V, S, M',
          duration: 'Concentration, up to 10 minutes',
          school: 'Abjuration',
          target: 'One Willing Creature',
          area_of_effect: '',
          phb_page: 270
        },
        {
          id: 74,
          name: 'Purify Food and Drink',
          level: 1,
          casting_time: '1 Action',
          range: '10 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Transmutation',
          target: 'Nonmagical food and drink',
          area_of_effect: '',
          phb_page: 270
        },
        {
          id: 75,
          name: 'Ray of Sickness',
          level: 1,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Necromancy',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 271
        },
        {
          id: 76,
          name: 'Sanctuary',
          level: 1,
          casting_time: '1 Bonus Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: '1 minute',
          school: 'Abjuration',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 272
        },
        {
          id: 77,
          name: 'Searing Smite',
          level: 1,
          casting_time: '1 Bonus Action',
          range: 'Self',
          components: 'V',
          duration: 'Concentration, up to 1 minute',
          school: 'Evocation',
          target: '',
          area_of_effect: '',
          phb_page: 274
        },
        {
          id: 78,
          name: 'Shield',
          level: 1,
          casting_time: '1 Reaction',
          range: 'Self',
          components: 'V, S',
          duration: '1 Round',
          school: 'Abjuration',
          target: '',
          area_of_effect: '',
          phb_page: 275
        },
        {
          id: 79,
          name: 'Shield of Faith',
          level: 1,
          casting_time: '1 Bonus Action',
          range: '60 ft',
          components: 'V, S, M',
          duration: 'Concentration, up to 10 minutes',
          school: 'Abjuration',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 275
        },
        {
          id: 80,
          name: 'Silent Image',
          level: 1,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V, S, M',
          duration: 'Concentration, up to 10 minutes',
          school: 'Illusion',
          target: '',
          area_of_effect: '',
          phb_page: 276
        },
        {
          id: 81,
          name: 'Sleep',
          level: 1,
          casting_time: '1 Action',
          range: '90 ft',
          components: 'V, S, M',
          duration: '1 minute',
          school: 'Enchantment',
          target: 'All Creatures',
          area_of_effect: '20 ft radius Sphere',
          phb_page: 276
        },
        {
          id: 82,
          name: 'Speak with Animals',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S',
          duration: '10 minutes',
          school: 'Divination',
          target: '',
          area_of_effect: '',
          phb_page: 277
        },
        {
          id: 83,
          name: "Tasha's Hideous Laughter",
          level: 1,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: 'Concentration, up to 1 minute',
          school: 'Enchantment',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 280
        },
        {
          id: 84,
          name: "Tenser's Floating Disk",
          level: 1,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: '1 hour',
          school: 'Conjuration',
          target: '',
          area_of_effect: '',
          phb_page: 282
        },
        {
          id: 85,
          name: 'Thunderous Smite',
          level: 1,
          casting_time: '1 Bonus Action',
          range: 'Self',
          components: 'V',
          duration: 'Concentration, up to 1 minute',
          school: 'Evocation',
          target: '',
          area_of_effect: '',
          phb_page: 282
        },
        {
          id: 86,
          name: 'Thuderwave',
          level: 1,
          casting_time: '1 Action',
          range: 'Self',
          components: 'V, S',
          duration: 'Instantaneous',
          school: 'Evocation',
          target: '',
          area_of_effect: '15 ft Cube',
          phb_page: 282
        },
        {
          id: 87,
          name: 'Unseen Servant',
          level: 1,
          casting_time: '1 Action',
          range: '60 ft',
          components: 'V, S, M',
          duration: '1 hour',
          school: 'Conjuration',
          target: '',
          area_of_effect: '',
          phb_page: 284
        },
        {
          id: 88,
          name: 'Witch Bolt',
          level: 1,
          casting_time: '1 Action',
          range: '30 ft',
          components: 'V, S, M',
          duration: 'Concentration, up to 1 minute',
          school: 'Evocation',
          target: 'One Creature',
          area_of_effect: '',
          phb_page: 289
        },
        {
          id: 89,
          name: 'Wrathful Smite',
          level: 1,
          casting_time: '1 Bonus Action',
          range: 'Self',
          components: 'V',
          duration: 'Concentration, up to 1 minute',
          school: '',
          target: '',
          area_of_effect: '',
          phb_page: 289
        }
      ]);
    });
};
