
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('race').del()
    .then(function () {
      // Inserts seed entries
      return knex('race').insert([
        {
          id: 1,
          name: 'Dwarf',
          skills: '',
          str_mod: 0,
          dex_mod: 0,
          con_mod: 2,
          int_mod: 0,
          wis_mod: 0,
          cha_mod: 0,
          age_min: 50,
          age_max: 400,
          size: 'Medium',
          speed: 25,
          alignments: 'LG, NG, CG, LN, N, CN, LE, NE',
          languages: 'Common, Dwarvish',
          weapon_profs: 'Battleaxe, Handaxe, Throwing Hammer, Warhammer',
          armor_profs: '',
          tool_profs: "Pick One: Smith's Tools, Brewer's Supplies, Mason's Tools",
          names_male: 'Adrik, Alberich, Baern, Barendd, Brottor, Bruenor, Dain, Darrak, Delg, Eberk, Einkil, Fargrim, Flint, Gardain, Harbek, Kildrak, Morgran, Orsik, Oskar, Rangrim, Rurik, Taklinn, Thoradin, Thorin, Tordek, Traubon, Travok, Ulfgar, Veit, Vondal',
          names_female: 'Amber, Artin, Audhild, Bardryn, Dagnal, Diesa, Eldeth, Falkrunn, Finellen, Gunnloda, Gurdis, Helja, Hlin, Kathra, Kristryd, Ilde, Liftrasa, Mardred, Riswynn, Sannl, Torbera, Torgga, Vistra',
          names_family_title: 'Clan Names',
          names_family: 'Balderk, Battlehammer, Brawnanvil, Dankil, Fireforge, Frostbeard, Gorunn, Holderhek, Ironfist, Loderr, Lutgehr, Rumnaheim, Strakeln, Torunn, Ungart',
          phb_page: 18
        },
        {
          id: 2,
          name: 'Elf',
          skills: 'Perception',
          str_mod: 0,
          dex_mod: 2,
          con_mod: 0,
          int_mod: 0,
          wis_mod: 0,
          cha_mod: 0,
          age_min: 100,
          age_max: 750,
          size: 'Medium',
          speed: 30,
          alignments: 'LG, NG, CG, LN, N, CN, NE, CE',
          languages: 'Common, Elvish',
          weapon_profs: '',
          armor_profs: '',
          tool_profs: "",
          names_male: 'Adran, Aelar, Aramil, Arannis, Aust, Beiro, Berrian, Carric , Enialis, Erdan, Erevan, Galinndan, Hadarai, Heian, Himo, Immeral, Ivellios, Laucian, Mindartis, Paelias, Peren, Quarion, Riardon, Rolen, Soveliss, Thamior, Tharivol, Theren, Varis',
          names_female: 'Adrie, Althaea, Anastrianna, Andraste, Antinua, Bethrynna, Birel, Caelynn, Drusilia, Enna, Felosial, Ielenia, Jelenneth, Keyleth, Leshanna, Lia, Meriele, Mialee, Naivara, Quelenna, Quillathe, Sariel, Shanairra, Shava, Silaqui, Theirastra, Thia, Vadania, Valanthe, Xanaphia',
          names_family_title: 'Family Names (Common Translations)',
          names_family: "Amakiir (Gemflower), Amastacia (Starflower), Galanodel (Moonwhisper), Holimion (Diamonddew), Ilphelkiir (Gemblossom), Liadon (Silverfrond), Meliamne (Oakenheel), Nai'lo (Nightbreeze), Siannodel (Moonbrook), Xiloscient (Goldpetal)",
          phb_page: 21
        },
        {
          id: 3,
          name: 'Halfling',
          skills: '',
          str_mod: 0,
          dex_mod: 2,
          con_mod: 0,
          int_mod: 0,
          wis_mod: 0,
          cha_mod: 0,
          age_min: 20,
          age_max: 150,
          size: 'Small',
          speed: 25,
          alignments: 'LG, NG, CG, LN, N, CN, LE, NE',
          languages: 'Common, Halfling',
          weapon_profs: '',
          armor_profs: '',
          tool_profs: "",
          names_male: 'Alton, Ander, Cade, Corrin, Eldon, Errich, Finnan, Garret, Lindal, Lyle, Merric, Milo, Osborn, Perrin, Reed, Roscoe, Wellby',
          names_female: 'Andry, Bree, Callie, Cora, Euphemia, Jillian, Kithri, Lavinia, Lidda, Merla, Nedda, Paela, Portia, Seraphina, Shaena, Trym, Vani, Verna',
          names_family_title: 'Family Names',
          names_family: 'Brushgather, Goodbarrel, Greenbottle, High-hill, Hilltopple, Leagallow, Tealeaf, Thorngage, Tosscobble, Underbough',
          phb_page: 26
        },
        {
          id: 4,
          name: 'Human',
          skills: '',
          str_mod: 1,
          dex_mod: 1,
          con_mod: 1,
          int_mod: 1,
          wis_mod: 1,
          cha_mod: 1,
          age_min: 16,
          age_max: 100,
          size: 'Medium',
          speed: 30,
          alignments: 'LG, NG, CG, LN, N, CN, LE, NE, CE',
          languages: 'Common, +1',
          weapon_profs: '',
          armor_profs: '',
          tool_profs: "",
          names_male: '(Calishite) Aseir, Bardeid, Haseid, Khemed,Mehmen,Sudeiman,Zasheir, (Chondathan) Darvin, Dorn, Evendur, Gorstag, Grim, Helm, Malark, Morn, Randal, Stedd, (Damaran) Bor, Fodel, Glar, Grigor, Igan, Ivor, Kosef, Mival, Orel, Pavel, Sergor, (Illuskan) Ander, Blath, Bran, Frath, Geth, Lander, Luth, Malcer, Stor, Taman, Urth, (Mulan) Aoth, Bareris, Ehput-Ki, Kethoth, Mumed, Ramas, So-Kehur, Thazar-De, Urhur, (Rashemi) Borivik, Faurgar, Jandar, Kanithar, Madislak, Ralmevik, Shaumar, Vladislak, (Shou) An, Chen, Chi, Fai, Jiang, Jun, Lian, Long, Meng, On, Shan, Shui, Wen, (Turami) Anton, Diero, Marcon, Pieron, Rimardo, Romero, Salazar, Umbero',
          names_female: '(Calishite) Atala, Ceidil, Hama, Jasmal, Meilil, Seipora, Yasheira, Zasheida, (Chondathan) Arveene, Esvele, Jhessail, Kerri, Lureene, Miri, Rowan, Shandri, Tessele, (Damaran) Alethra, Kara, Katernin, Mara, Natali, Olma, Tana, Zora, (Illuskan) Amafrey, Betha, Cefrey, Kethra, Mara, Olga, Silifrey, Westra;, (Mulan) Arizima, Chathi, Nephis, Nulara, Murithi, Sefris, Thola, Umara, Zolis, (Rashemi) Fyevarra, Hulmarra, Immith, Imzel, Navarra, Shevarra, Tammith. Yuldra, (Shou) Bai, Chao, Jia, Lei, Mei, Qiao, Shui, Tai, (Turami) Balama, Dona, Faila, Jalana, Luisa, Marta, Quara, Selise, Vonda',
          names_family_title: 'Family Names',
          names_family: '(Calishite) Basha, Dumein, Jassan, Khalid, Mostana, Pashar, Rein, (Chondathan) Amblecrown, Buckman, Dundragon, Evenwood, Greycastle, Tallstag, (Damaran) Bersk, Chernin, Dotsk, Kulenov, Marsk, Nemetsk, Shemov, Starag, (Illuskan) Brightwood, Helder, Hornraven, Lackman, Stormwind, Windrivver, (Mulan) Ankhalab, Anskuld, Fezim, Hahpet, Nathandem, Sepret, Uuthrakt, (Rashemi) Chergoba, Dyernina, Iltazyara, Murnyethara, Stayanoga, Ulmokina, (Shou) Chien, Huang, Kao, Kung, Lao, Ling, Mei, Pin, Shin, Sum, Tan, Wan, (Turami) Agosto, Astorio, Calabra, Domine, Falone, Marivaldi, Pisacar, Ramondo',
          phb_page: 29
        },
        {
          id: 5,
          name: 'Dragonborn',
          skills: '',
          str_mod: 2,
          dex_mod: 0,
          con_mod: 0,
          int_mod: 0,
          wis_mod: 0,
          cha_mod: 1,
          age_min: 15,
          age_max: 80,
          size: 'Medium',
          speed: 30,
          alignments: 'LG, NG, CG, LN, CN, LE, NE, CE',
          languages: 'Common, Draconic',
          weapon_profs: '',
          armor_profs: '',
          tool_profs: "",
          names_male: 'Arjhan, Balasar, Bharash, Donaar, Ghesh. Heskan, Kriv, Medrash, Mehen, Nadarr, Pandjed, Patrin, Rhogar, Shamash, Shedinn, Tarhun, Torinn',
          names_female: 'Akra, Biri, Daar, Farideh, Harann, Flavilar, Jheri, Kava, Korinn, Mishann, Nala, Perra, Raiann, Sora, Surina, Thava, Uadjit',
          names_family_title: 'Clan Names',
          names_family: 'Clethtinthiallor, Daardendrian, Delmirev, Drachedandion, Fenkenkabradon, Kepeshkmolik, Kerrhylon, Kimbatuul, Linxakasendalor, Myastan, Nemmonis, Norixius, Ophinshtalajiir, Prexijandilin, Shestendeliath, Turnuroth, Verthisathurgiesh, Yarjerit',
          phb_page: 32
        },
        {
          id: 6,
          name: 'Gnome',
          skills: '',
          str_mod: 0,
          dex_mod: 0,
          con_mod: 0,
          int_mod: 2,
          wis_mod: 0,
          cha_mod: 0,
          age_min: 40,
          age_max: 450,
          size: 'Small',
          speed: 25,
          alignments: 'LG, NG, CG, LN, N, CN',
          languages: 'Common, Gnomish',
          weapon_profs: '',
          armor_profs: '',
          tool_profs: "",
          names_male: 'Alston, Alvyn, Boddynock, Brocc, Burgell, Dimble, Eldon, Erky, Fonkin, Frug, Gerbo, Gimble, Glim, Jebeddo, Kellen, Namfoodle, Orryn, Roondar, Seebo, Sindri, Warryn, Wrenn, Zook',
          names_female: 'Bimpnottin, Breena, Caramip, Carlin, Donella, Duvamil, Ella, Ellyjobell, Ellywick, Lilli, Loopmottin, Lorilla, Mardnab, Nissa, Nyx, Oda, Orla, Roywyn, Shamil, Tana, Waywocket, Zanna',
          names_family_title: 'Clan Names',
          names_family: 'Beren, Daergel, Folkor, Garrick, Nackle, Murnig, Ningel, Raulnor, Scheppen, Timbers, Turen',
          phb_page: 35
        },
        {
          id: 7,
          name: 'Half-Elf',
          skills: '+2',
          str_mod: 0,
          dex_mod: 0,
          con_mod: 0,
          int_mod: 0,
          wis_mod: 0,
          cha_mod: 2,
          age_min: 20,
          age_max: 180,
          size: 'Medium',
          speed: 30,
          alignments: 'LG, NG, CG, LN, N, CN, NE, CE',
          languages: 'Common, Elvish, +1',
          weapon_profs: '',
          armor_profs: '',
          tool_profs: "",
          names_male: '',
          names_female: '',
          names_family_title: '',
          names_family: '',
          phb_page: 38
        },
        {
          id: 8,
          name: 'Half-Orc',
          skills: 'Intimidation',
          str_mod: 2,
          dex_mod: 0,
          con_mod: 1,
          int_mod: 0,
          wis_mod: 0,
          cha_mod: 0,
          age_min: 14,
          age_max: 75,
          size: 'Medium',
          speed: 30,
          alignments: 'CG, LN, N, CN, LE, NE, CE',
          languages: 'Common, Orc',
          weapon_profs: '',
          armor_profs: '',
          tool_profs: "",
          names_male: 'Dench, Feng, Gell, Henk, Holg, Imsh, Keth, Krusk, Mhurren, Ront, Shump, Thokk',
          names_female: 'Baggi, Emen, Engong, Kansif, Myev, Neega, Ovak, Ownka, Shautha, Sutha, Vola, Volen, Yevelda',
          names_family_title: '',
          names_family: '',
          phb_page: 40
        },
        {
          id: 9,
          name: 'Tiefling',
          skills: '',
          str_mod: 0,
          dex_mod: 0,
          con_mod: 0,
          int_mod: 1,
          wis_mod: 0,
          cha_mod: 2,
          age_min: 16,
          age_max: 125,
          size: 'Medium',
          speed: 30,
          alignments: 'CG, N, CN, LE, NE, CG',
          languages: 'Common, Infernal',
          weapon_profs: '',
          armor_profs: '',
          tool_profs: "",
          names_male: 'Akmenos, Amnon, Barakas, Damakos, Ekemon, Iados, Kairon, Leucis, Melech, Mordai, Morthos, Pelaios, Skamos, Therai',
          names_female: 'Akta, Anakis, Bryseis, Criella, Damaia, Ea, Kallista, Lerissa, Makaria, Nemeia, Orianna, Phelaia, Rieta',
          names_family_title: '"Virtue" Names',
          names_family: 'Art, Carrion, Chant, Creed, Despair, Excellence, Fear, Glory, Hope, Ideal, Music, Nowhere, Open, Poetry, Quest, Random, Reverence, Sorrow, Temerity, Torment, Weary',
          phb_page: 42
        }
      ]);
    });
};
